[package]
name = "day5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ranges = "*"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "sandbox"
path = "src/sandbox.rs"